### ISSUE TITLE
could you please tell the specific environment requirements,i cant run this

### ISSUE THREAD

**Issue by DOGHEADLIKE** [LucaAngioloni/ProteinSecondaryStructure-CNN#1]
such as tensorflow and keras versions ,please

**Comment by LucaAngioloni** [comment]
Hi, thanks for your interest in my research.

This project as of 2017 when it was written was using the old version of Tensorflow/Keras (v1). I tried to replicate something similar and I got the following environment working:

- tensorboard (1.15.0)
- tensorflow-estimator (1.15.1)
- tensorflow-gpu (1.15.4)
- scikit-learn (0.19.1)
- scipy (1.4.1)
- numpy (1.18.4)
- matplotlib (2.1.1)
- Keras (2.3.1)
- Keras-Applications (1.0.8)
- Keras-Preprocessing (1.1.2)

I am training it right now and I think I am getting the same results.

Let me know if you can make it work too. And feel free to try and rewrite this in TF 2.

**Comment by DOGHEADLIKE** [comment]
Thank you for your reply and my problem is solved.Have a good day!
