### ISSUE TITLE
dataset unavailable

### ISSUE THREAD

**Issue by PastelBelem8** [LucaAngioloni/ProteinSecondaryStructure-CNN#11]
Hey! i'd like to try running your model but can't download the data. would it be possible for you to give it to me, pretty please?

**Comment by PastelBelem8** [comment]
I found it here: https://zenodo.org/record/7764556#.ZByi1ezMJvI

**Comment by LucaAngioloni** [comment]
Hi! 
Sorry, over the years the original link to the dataset has gone offline. 
The link you provided is a good alternative. 

I will update the readme file with that too.

Thank you!

**Comment by LucaAngioloni** [comment]
I am closing this issue.
