### ISSUE TITLE
	cullpdb+profile_6133_filtered.npy.gz	

### ISSUE THREAD

**Issue by deekshaVarshney** [LucaAngioloni/ProteinSecondaryStructure-CNN#2]
Unable to open this file using this 
data = np.load(gzip.open('data/cullpdb+profile_6133_filtered.npy.gz', 'rb'))

Error
gzip.BadGzipFile: Not a gzipped file (b'\x93N')

**Comment by LucaAngioloni** [comment]
Hi, this is weird but it looks like the file you have is already uncompressed and is not gzipped anymore.

Can you check the file size? 
If gzipped it should be around 100 MB while the uncompressed version is around 1.7 GB.

This can happen sometimes if you downloaded the file with `wget` for example. It reads the Mime Type and automatically uncompresses the file while leaving the `.gz` in the filename.

If this is the case just remove the `.gz` from the file name and load it with numpy.

**Comment by LucaAngioloni** [comment]
@deekshaVarshney did you solve your problem?

I will consider this issue resolved as of now unless I hear from you again.
